[package]
name = "kos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv = { version = "0.10.1" }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

[profile.release]
debug = true
opt-level = 0


[[bin]]
name = "kos"
path = "src/main.rs"