[package]
name = "user_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 由于我们定义了自己的用户级 panic, 因此在编译本库的时候禁用 kernel 的 panic
sys_interface = {path = "../sys_interface"}
logger = {path = "../logger", features = ["user"]}
spin = "0.9.6"

[profile.release]
debug = true
opt-level = 0

