[package]
name = "user"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
user_lib = { path = "../user_lib" }

[profile.release]
debug = true



# -----------------------------------------
[[bin]]
name = "hello"
path = "src/hello.rs"

# 执行高优先级指令，应该被 kill
[[bin]]
name = "priv_inst"
path = "src/priv_inst.rs"

# 执行 0 地址写入，应该被 kill
[[bin]]
name = "store_fault"
path = "src/store_fault.rs"

[[bin]]
name = "power"
path = "src/power.rs"